# Generated by Django 6.0.5 on 2026-06-04 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('cvss_score', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('source', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('epss_score', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('application_name', models.CharField(max_length=200)),
                ('version', models.CharField(max_length=200)),
                ('published_date', models.DateField()),
                ('date_added', models.DateField()),
                ('last_modification_date', models.DateField()),
                ('is_kev', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'vulnerabilities',
                'db_table': 'vulnerabilities',
                'ordering': ['-cvss_score'],
            },
        ),
    ]
