# Generated by Django 6.0.5 on 2026-06-11 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerabilities', '0003_alter_vulnerability_epss_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffectedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(blank=True, max_length=300, null=True)),
                ('name', models.CharField(max_length=200)),
                ('version', models.JSONField(blank=True, default=list, null=True)),
                ('vulnerability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affected_products', to='vulnerabilities.vulnerability', to_field='cve_id')),
            ],
            options={
                'verbose_name_plural': 'affected products',
            },
        ),
    ]
