# Generated by Django 6.0.5 on 2026-06-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerabilities', '0004_affectedproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affectedproduct',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
