# Generated by Django 6.0.5 on 2026-06-12 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerabilities', '0005_alter_affectedproduct_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='affectedproduct',
            unique_together={('vulnerability', 'name')},
        ),
    ]
