# Generated by Django 6.0.5 on 2026-06-12 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerabilities', '0006_alter_affectedproduct_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='affectedproduct',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='affectedproduct',
            name='vendor',
            field=models.CharField(default='unknown', max_length=300),
        ),
        migrations.AlterUniqueTogether(
            name='affectedproduct',
            unique_together={('vulnerability', 'vendor', 'name')},
        ),
    ]
